### ISSUE TITLE
Complex or sparse input following 'like' is not supported

### ISSUE THREAD

**Issue by Waves-base** [complexphoton/Imaging-simulations#1]
Hi,

Thanks for useful codes, here i find errors as listed below, i'm using 'Matlab-2020a' version, FYI

Error as follows 
`Error using randn Complex or sparse input following 'like' is not supported.`

`Error in recon_smt (line 62)`
        `R = R + noise_amp*sqrt(mean(abs(R).^2, 'all'))*randn(size(R), 'like', 1j);`
`Error in recon_all (line 5)`
`recon_smt(data_dir); % reconstruct the SMT image`

**Comment by zywang36** [comment]
Hi Waves-base,

Good catch! The error comes from the old Matlab version. The input of randn() function used there was not supported until R2022a (https://www.mathworks.com/help/matlab/ref/randn.html). I will push an update later to fix that. 

Best,
Zeyu
